### PR TITLE
Adopt site interface for build scripts

### PR DESCRIPTION
**Pull request by abunashir**
**Context**

Recently, we've added a `site` interface to replace the old Makefiles to generate min site, so now we don't necessarily need
to copy over these files in each repo and we can also start using it directly in the actions.

This commit removes the Makefiles and it also updates the build scripts for those sample and template repository.

**Further cleanup**

There are two mainly: first of all, we will need to remove those file references from the `cims.yml` file, so it doesn't try to
copy these over and we also need to look into the CI packages like `yq`, if we still need those for anything else.

### CODE REVIEW

**Comment by abunashir** [comment]
This is also partially dependent on this - https://github.com/metanorma/metanorma-cli/pull/199, so once that released then we will need to push those updates to each repo. 

//cc: @CAMOBAP , @ronaldtse

**Comment by CAMOBAP** [comment]
@abunashir `cimas-config/cimas.yml` need to be updated too, please let me know if you need help with this

**Comment by ronaldtse** [comment]
> `cimas-config/cimas.yml` need to be updated too, please let me know if you need help with this

@CAMOBAP could you help run Cimas to check if the rfc-* workflows work? Thanks!

**Comment by CAMOBAP** [comment]
> @CAMOBAP could you help run Cimas to check if the rfc-* workflows work? Thanks!

Sure, once the new metanorma will be released I will do this

**Comment by ronaldtse** [comment]
Thanks!

**Pull request merged**
